version: '3'
services:
    db:
        image: postgres:13
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: db
            POSTGRES_HOST_AUTH_METHOD: trust
    cache:
        image: redis:6
        ports:
            - '6379:6379'
    web:
        stdin_open: true
        tty: true
        build: .
        volumes:
            - .:/prueba
        ports:
            - '8000:8000'
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
            - cache